#!/bin/bash
# just build manually instead of trying
# to do fancy webpack stuff.
# This is only used for the twinkling effect
# on the home page.

cd "$(dirname "${BASH_SOURCE[0]}")" || exit
cd elm || exit
elm make src/Stars.elm --optimize --output=./../assets/stars.js
